[ADD] new module account_voucher_print
OCA/account-financial-tools pull request #1014
Opened 2020-07-03 08:49 UTC by primes2h

This module allows to print sale and purchase receipts.

2020-07-03 11:40 UTC, HaraldPanten approved these changes
Functional review 👍

2020-07-03 15:29 UTC, marcelsavegnago approved these changes

2020-07-05 10:08 UTC, marcelofrare approved these changes
functional LGTM

2020-07-09 17:14 UTC, sergiocorato requested changes

2020-07-09 17:14 UTC, sergiocorato commented on account_voucher_print/views/report_receipt.xml
> +    <data>
`<data>` is no more needed

2020-07-10 12:54 UTC, sergiocorato requested changes

2020-07-10 12:54 UTC, sergiocorato commented on account_voucher_print/__manifest__.py
> +    'auto_install': False,
```suggestion
```

2020-07-10 12:54 UTC, sergiocorato commented on account_voucher_print/views/account_report.xml
> +    <data>
other unuseful `<data>`

2020-07-10 13:10 UTC, primes2h commented on account_voucher_print/views/report_receipt.xml
> +    <data>
Removed, thanks!

2020-07-10 13:10 UTC, primes2h commented on account_voucher_print/views/account_report.xml
> +    <data>
Removed as well, thanks!

2020-07-10 13:10 UTC, primes2h commented on account_voucher_print/__manifest__.py
> +    'auto_install': False,
Done.

2020-07-10 15:42 UTC, sergiocorato approved these changes

2020-07-11 08:24 UTC, sergiocorato commented
/ocabot merge nobump

2020-07-11 08:52 UTC, merged