[13.0] account_chart_update FIX: not delete tax repartition lines
OCA/account-financial-tools pull request #1052
Opened 2020-09-03 15:31 UTC by celm1990

When update taxes and only change account_id(on repartition lines), in BD with data is impossible run this wizard because try delete repartition lines but ondelete=restrict in account.move.line avoid this unlink. see https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_move.py#L2587-L2588

![image](https://user-images.githubusercontent.com/7775116/92134496-3582d000-edcf-11ea-8e2f-21a91d56594e.png)

Before, commands to execute are: `create`(0, 0, vals) and `unlink`(2, ID)
![image](https://user-images.githubusercontent.com/7775116/92134587-51867180-edcf-11ea-9d12-f484e4179a82.png)

after commit, commands are: `write `(1, ID, vals) if account has changes

**Note**: logger show `warning to comparing apples and orange`, see https://github.com/OCA/account-financial-tools/blob/13.0/account_chart_update/wizard/wizard_chart_update.py#L687 because operator left is `list(dict)` and operator right is `recordset`. this change is out commit scope only is observation.

![image](https://user-images.githubusercontent.com/7775116/92135066-eab58800-edcf-11ea-9659-da65a9509c6a.png)

2020-09-03 15:35 UTC, pedrobaeza commented
Can you please create a test exercising the problem?

2020-09-15 10:38 UTC, luc-demeyer commented
I encountered the same issue but figured out that the tax update encounters several other issues hence I ended up with a refactoring of the tax update functionality, cf. https://github.com/OCA/account-financial-tools/pull/1056

2020-09-15 10:39 UTC, luc-demeyer requested changes
incomplete fix, cf. refactoring in https://github.com/OCA/account-financial-tools/pull/1056

2021-11-12 07:31 UTC, pedrobaeza commented
Superseded by #1251

2021-11-12 07:31 UTC, closed without merging