[14.0][MIG] account_move_force_removal module
OCA/account-financial-tools pull request #1167
Opened 2021-04-26 08:43 UTC by tafaRU

2021-04-26 13:06 UTC, victoralmau requested changes

2021-04-26 13:06 UTC, victoralmau commented on account_move_force_removal/tests/test_move.py
> +        )
```suggestion
       account_type = self.env.ref("account.data_account_type_other_income")
       cls.income_account = cls.env["account.account"].search(
            [("user_type_id", "=", account_type.id)], limit=1
        )
```

2021-04-26 13:18 UTC, tafaRU commented on account_move_force_removal/tests/test_move.py
> +        )
Thanks for the suggestion! Done.

2021-04-26 14:10 UTC, victoralmau approved these changes

2021-05-03 10:01 UTC, pedrobaeza approved these changes
You can squash administrative commits into the first real one (from v13).

2021-05-03 10:14 UTC, tafaRU commented
Thanks for the review @pedrobaeza 

About:
> You can squash administrative commits into the first real one (from v13).

It seems it's already done.

2021-05-03 10:22 UTC, pedrobaeza commented
No, it isnt':

![Selección_002](https://user-images.githubusercontent.com/7165771/116865601-398b1a00-ac0a-11eb-940f-1b8c40d9b509.png)

2021-05-03 13:23 UTC, tafaRU commented
/ocabot merge nobump

2021-05-03 13:43 UTC, merged