[14.0][ADD] account_move_line_check_number
OCA/account-financial-tools pull request #1236
Opened 2021-09-13 16:40 UTC by ps-tubtim

This module adds the check number in the journal items.

**Example**
![Selection_145](https://user-images.githubusercontent.com/51266019/133122612-5092d4e9-3691-44a0-9542-1d36b14c691e.png)

**Note:** You can use this module and `bank_statement_check_number` (https://github.com/OCA/account-reconcile/pull/402) to help to reconcile by check number.

2022-05-17 07:14 UTC, Saran440 approved these changes
LGTM :+1:

2022-08-30 12:28 UTC, ChrisOForgeFlow requested changes

2022-08-30 12:28 UTC, ChrisOForgeFlow commented on account_move_line_check_number/models/account_move.py
> +            rec.check_number = rec.payment_id and rec.payment_id.check_number or ""
Is more efficient read direct field, if empty should return empty string
```suggestion
            rec.check_number = rec.payment_id.check_number or ""
```

2022-09-14 10:34 UTC, Saran440 commented
@ChrisOForgeFlow Thank you for your advise, please review and approve (if it okay)

2022-09-14 12:24 UTC, ChrisOForgeFlow approved these changes
LGTM

2022-09-15 01:57 UTC, kittiu commented
/ocabot merge nobump

2022-09-15 02:10 UTC, merged