[14.0][MIG] account_spread_cost_revenue
OCA/account-financial-tools pull request #1244
Opened 2021-10-01 09:57 UTC by kittiu

Standard migration

2021-10-01 09:59 UTC, kittiu commented
@astirpe I have made the migration of the module out of your PR. Most seem ok. Except here,
https://github.com/OCA/account-financial-tools/pull/1244/files#diff-c57937ecf6269df4b995260fb68911ef84a4c3d11f51ab5aa91f5144d705ea52R40

I need to add this as v13 is allowed to reconciled without posted state, but not in v14.

2021-10-01 12:47 UTC, astirpe requested changes
@kittiu I can't test it on Runbot but I tried locally and I got this error:

```
The sequence regex should at least contain the seq grouping keys. For instance:
^(?P<prefix1>.*?)(?P<seq>\d*)(?P<suffix>\D*?)$
```

To reproduce it just click on the "Create Move" button on any spread line

2021-10-01 12:47 UTC, astirpe commented on account_spread_cost_revenue/views/account_spread.xml
> +                                        attrs="{'invisible':['|',('move_id','!=',False)]}"
```suggestion
                                        attrs="{'invisible':[('move_id','!=',False)]}"
```

2021-10-01 16:27 UTC, kittiu commented on account_spread_cost_revenue/views/account_spread.xml
> +                                        attrs="{'invisible':['|',('move_id','!=',False)]}"
Fixed!

2021-10-02 07:37 UTC, kittiu commented
May I explain the main point of change on this MIG,

**Odoo 13**
Odoo can reconcile move lines, even on state "draft". And so, the logic and test is also to prove that.
(which actually not quite correct in my opinion). 

**Odoo 14**
Only reconcile after posting document.

* https://github.com/OCA/account-financial-tools/pull/1244/commits/470d872ff65a797aa6aa308a79d2334c577a7bb0#diff-c57937ecf6269df4b995260fb68911ef84a4c3d11f51ab5aa91f5144d705ea52L38-L39
* https://github.com/OCA/account-financial-tools/pull/1244/commits/470d872ff65a797aa6aa308a79d2334c577a7bb0#diff-50788f2526bc0ec75ae627daa97d005c29444834c499e006b0ea77f79d57d6a9R501-R502
* https://github.com/OCA/account-financial-tools/pull/1244/commits/470d872ff65a797aa6aa308a79d2334c577a7bb0#diff-e279bec9360828ba2ebeb82a3b26b82424e049b4a6e547c1d74aa5cbaa7b81c4R16-R20

2021-10-02 09:30 UTC, kittiu commented
Looks like new Numbering cause a lot of problem. When create_move() this module use Description from spread table as Number of Journal Entry. And it always conflict with the pattern of v14.

May be we can change to use number of standard running number (MISC/...) instead?

@astirpe WDYT?

2021-10-04 06:19 UTC, astirpe commented
@kittiu yes, I agree

2021-10-04 06:57 UTC, kittiu commented
> @kittiu yes, I agree

Fixed.

2021-10-05 08:36 UTC, astirpe commented
I made a quick test locally and it seems working fine! I would like to spend some extra time to test more in deep, unless there are other contributors who want to do that.

2022-02-18 02:32 UTC, ps-tubtim approved these changes
LGTM.

2022-03-23 03:21 UTC, Saran440 approved these changes
LGTM :+1:

2022-03-24 00:40 UTC, rafaelbn commented
/ocabot migration account_spread_cost_revenue

2022-06-01 12:40 UTC, hitrosol commented
@kittiu, I can't test this PR since it still refer to runbot instead of runboat.

2022-08-16 12:38 UTC, espo-tony approved these changes

2022-10-18 06:24 UTC, kittiu commented
/ocbot merge nobump

2022-10-18 06:36 UTC, astirpe approved these changes

2022-10-18 08:00 UTC, Saran440 commented
@kittiu you use wrong typo command. please do it again.

2022-10-24 18:38 UTC, kittiu commented
/ocabot merge nobump

2022-11-18 11:49 UTC, luc-demeyer approved these changes

2022-11-18 11:51 UTC, luc-demeyer commented
Code review & testing ok.
Pls merge.

2022-11-21 12:55 UTC, luc-demeyer commented on account_spread_cost_revenue/security/ir.model.access.csv
> +id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
read access should be added for account.group_account_invoice

2022-11-21 12:56 UTC, luc-demeyer requested changes
read access must added for the spread models for account.group_account_invoice

2023-01-20 08:01 UTC, StefanRijnhart commented
@kittiu would you like to address the permission comment by @luc-demeyer?

2023-01-20 10:45 UTC, Saran440 commented
@StefanRijnhart @luc-demeyer Fixed it. can you check please?

2023-01-20 10:59 UTC, StefanRijnhart commented
Looking good! Can you squash the new commit into the migration commit?

2023-01-20 11:02 UTC, StefanRijnhart approved these changes
Thanks for the quick follow-up! @luc-demeyer is it OK for you now?

2023-02-06 08:13 UTC, Saran440 commented
@StefanRijnhart @luc-demeyer  Hi, let's merge this pull request. We will continue to migrate this module to version 15.

2023-02-07 10:41 UTC, StefanRijnhart commented
Agreed!

/ocabot merge nobump

2023-02-07 10:55 UTC, merged