[MIG] account_cost_center: Migration to 15.0
OCA/account-financial-tools pull request #1384
Opened 2022-04-29 09:28 UTC by smemon786

2022-04-29 09:33 UTC, smemon786 commented
@aisopuro Please review it.

2022-05-17 03:54 UTC, kittiu commented
Hello, thanks for contributing.
Please make sure you follow the guideline in order to migrate https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

2022-05-31 07:29 UTC, smemon786 commented
@kittiu + @aisopuro this module is ready to merge.

2022-05-31 07:32 UTC, smemon786 commented
> Hello, thanks for contributing. Please make sure you follow the guideline in order to migrate https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

@kittiu, this module is ready to merge, please have a look.

2022-05-31 08:32 UTC, aisopuro commented
@smemon786 it seems this PR is only 1 commit, but I suspect it should be several, in order to maintain the original history of the module.

The link you've added is for migrating a module _that existed in 14.0_ to 15.0. But it looks like `account_cost_center` hasn't been in the repo since version 12.0.

I think you need to adapt the commands you linked to use branch `12.0` where they refer to `14.0`. That way you'll retain the proper git history of the module.

I basically think the first set of commands should be

```
$ git clone https://github.com/OCA/$REPO -b 15.0
$ cd $REPO
$ git checkout -b 15.0-mig-$MODULE origin/15.0
$ git format-patch --keep-subject --stdout origin/15.0..origin/12.0 -- $MODULE | git am -3 --keep
$ pre-commit run -a  # to run black, isort and prettier (ignore pylint errors at this stage)
$ git add -A
$ git commit -m "[IMP] $MODULE: black, isort, prettier"  --no-verify  # it is important to do all formatting in one commit the first time
```

2022-05-31 09:36 UTC, smemon786 commented
> @smemon786 it seems this PR is only 1 commit, but I suspect it should be several, in order to maintain the original history of the module.
> 
> The link you've added is for migrating a module _that existed in 14.0_ to 15.0. But it looks like `account_cost_center` hasn't been in the repo since version 12.0.
> 
> I think you need to adapt the commands you linked to use branch `12.0` where they refer to `14.0`. That way you'll retain the proper git history of the module.
> 
> I basically think the first set of commands should be
> 
> ```
> $ git clone https://github.com/OCA/$REPO -b 15.0
> $ cd $REPO
> $ git checkout -b 15.0-mig-$MODULE origin/15.0
> $ git format-patch --keep-subject --stdout origin/15.0..origin/12.0 -- $MODULE | git am -3 --keep
> $ pre-commit run -a  # to run black, isort and prettier (ignore pylint errors at this stage)
> $ git add -A
> $ git commit -m "[IMP] $MODULE: black, isort, prettier"  --no-verify  # it is important to do all formatting in one commit the first time
> ```

@aisopuro, please review now.

2022-05-31 10:06 UTC, aisopuro requested changes

2022-05-31 10:06 UTC, aisopuro commented on account_cost_center/models/account_invoice_report.py
> +        return super()._select() + ", line.cost_center_id as cost_center_id"
This line is missed by coverage. Could we add a simple test to just `search_read` from `account.invoice.report`? I believe that should be enough to exercise this line.

2022-05-31 10:06 UTC, aisopuro commented on account_cost_center/models/account_invoice_report.py
> +        return super()._group_by() + ", line.cost_center_id"
Same as above, I think just doing a `search_read` should cover this line.

2022-06-03 09:10 UTC, aisopuro approved these changes

2022-11-03 12:52 UTC, anikeenko-viktor commented
Could you please @kittiu check and merge it?

2022-11-03 15:10 UTC, kittiu commented
@TheerayutEncoder can you help test?

2022-11-03 16:05 UTC, TheerayutEncoder commented
OK, I will test this PR tomorrow.
For make sure it work properly in v15!
@kittiu

2022-11-04 08:24 UTC, TheerayutEncoder commented
Hi!
No error occurred while I installed this module.
But I can not create **Cost Centers** menu because it does not have **Analytics accounting** in Configuration menu
I already installed **Invoicing** and **Analytic Accounting**.

or should I setting something first?
@aisopuro 
Thanks in advance

2022-11-06 14:26 UTC, TheerayutEncoder approved these changes
This module work on Odoo v15.0 [👍](https://emojipedia.org/thumbs-up/)

2022-11-22 12:22 UTC, anikeenko-viktor commented
Hi @kittiu, could you please merge this one?

2022-11-22 15:00 UTC, kittiu commented
/ocabot merge nobump

2022-11-22 15:11 UTC, merged