[14.0][IMP] account_move_line_purchase_info: script post_install for update references on new column  purchase_line_id from stock.move
OCA/account-financial-tools pull request #1395
Opened 2022-05-10 21:24 UTC by JordiBForgeFlow

[Forward port of ](https://github.com/OCA/account-financial-tools/pull/1349)

2022-05-10 22:31 UTC, celm1990 commented on account_move_line_purchase_info/hooks.py
> +# Copyright 2022 ForgeFlow, S.L.
Only curiosity, because original author is not keep

2022-05-10 22:31 UTC, celm1990 approved these changes

2022-05-11 15:44 UTC, AaronHForgeFlow requested changes

2022-05-11 15:44 UTC, AaronHForgeFlow commented on account_move_line_purchase_info/hooks.py
> +            SET purchase_line_id = sm.purchase_line_id, purchase_id = pol.order_id
```suggestion
            SET purchase_line_id = sm.purchase_line_id, purchase_order_id = pol.order_id
```

2022-09-23 17:13 UTC, JordiBForgeFlow commented
@AaronHForgeFlow this one is ready to merge

2024-03-10 12:19 UTC, closed without merging