[15.0][ADD] stock_account_no_auto_reconcile
OCA/account-financial-tools pull request #1460
Opened 2022-08-22 12:42 UTC by AaronHForgeFlow

Prevent to reconcile when posting invoices or validating pickings in PO/SO with posted invoices.

cc @ForgeFlow

2022-09-01 07:10 UTC, DavidJForgeFlow requested changes
Functional review :+1: code also LGTM!

2022-09-01 07:10 UTC, DavidJForgeFlow commented on stock_account_no_auto_reconcile/README.rst
> +* ForgeFlow S.L. <forgeflow@eficent.com>
to update email

2022-09-01 07:10 UTC, DavidJForgeFlow commented on stock_account_no_auto_reconcile/readme/CONTRIBUTORS.rst
> +* ForgeFlow S.L. <forgeflow@eficent.com>
to update email

2022-10-17 11:44 UTC, AaronHForgeFlow commented
@DavidJForgeFlow comments attended :)

2022-12-19 13:35 UTC, DavidJForgeFlow approved these changes
LGTM! :+1:

2023-10-10 10:20 UTC, MiquelRForgeFlow approved these changes

2023-10-10 11:19 UTC, JordiBForgeFlow commented
/ocabot merge nobump

2023-10-10 11:30 UTC, merged