[14.0][FIX] account_asset_management: Poor performance updating assets massively
OCA/account-financial-tools pull request #1502
Opened 2022-11-22 16:06 UTC by KNVx

When updating assets massively the performance when searching for deprecation_lines_ids is very low. 
It is a difficult problem to detect since massive asset updates are not common.
 Indexing in this field dramatically improves the timing performance. 
For example, to update 3000 records it took 30 sec. With this index it takes to 2 seconds.

cc @eantones

2022-11-22 16:17 UTC, eantones commented
LGTM!

2022-11-22 16:17 UTC, eantones approved these changes

2022-11-26 11:50 UTC, pedrobaeza requested changes
A one2many field can't be indexed by definition. Also adding 2 contributors lines that will redo several files just for this seems overkill.

2022-11-26 11:51 UTC, pedrobaeza commented
You have to put the index in the inverse name of the child model (if not present already).

2022-12-01 16:08 UTC, KNVx commented
Thanks for pointing out the error, it was a problem transcribing the code from test.
As I said, it'
![deprecation_line_ids](https://user-images.githubusercontent.com/92428614/205101268-36a19e7e-4d7b-4b25-b405-b188b9dd5e19.png)
s a problem that occurs in the write of the assets, which call the function _create_first_asset_line. In the check "if self.depreciation_base and not self.depreciation_line_ids:" it takes a long time.
I attach additionally an image of the tests performed with pyspy.

2022-12-02 08:37 UTC, pedrobaeza approved these changes

2022-12-02 08:37 UTC, pedrobaeza commented
/ocabot merge minor

2022-12-02 08:43 UTC, merged