[16.0][IMP] account_fiscal_year add fields on res.company
OCA/account-financial-tools pull request #1506
Opened 2022-11-26 21:18 UTC by legalsylvain

Hi, three simple commits to improve ``account_fiscal_year`` module.

- 359b71b24b1f6e2a5201fff1cf079812d5d21ebb : factorize code, adding a new function in account.fiscal.year model.
- b920c77440fda7e7e907a5b6dae931c36c99b134 : Add fields start date and end date of the current fiscal year on res.company model, and display on the views
- c68335bf3c17324b33a273015775765c7aee90bb :  improve documentation, adding screenshots

### New description

This module allows to create and edit fiscal years from the menu:

Invoicing > Configuration > Accounting > Fiscal Years

![account_fiscal_year_form](https://user-images.githubusercontent.com/3407482/204109273-d02d0345-7522-499b-abb6-6263c1512e93.png)

The start and end dates of the current fiscal years are then available in the company tree and form views.

![res_company_tree](https://user-images.githubusercontent.com/3407482/204109280-bf877961-df6b-4c35-8191-d41429271009.png)

2022-11-26 21:19 UTC, legalsylvain commented
CC : last contributors : @baimont, @MiquelRForgeFlow, @SirTakobi, @pegonzalezspesol, @AlvaroTForgeFlow

2022-11-28 16:05 UTC, SirTakobi requested changes
Thanks for the PR!

About the commit messages, in general they should explain _why_ a change is done, not _what_ is done: the _what_ can be seen by the changes.
Also please follow https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message, more specifically:

- The commit message
  > [REF] account_fiscal_year : factorize code

  does not explain _why_ that change is done, but only _what_ is done (also, **[REF]** already says that there is a refactoring); it might be changed with something like _allow to override fiscal year search_ or _do not repeat same search_?
- There is no **[DOC]** prefix (I would squash it with the **[IMP]** commit)
- The commit message
  > [IMP] account_fiscal_year : Add fields start date and end date of the current fiscal year on res.company model, and display on the views
  
  is too long, and also does not explain _why_ that change is done, but only _what_ is done

The only thing that has to be changed is editing the **po(t)** file.
Everything else is just nitpicking :smile: and is not _really_ needed for merge in my opinion.

2022-11-28 16:05 UTC, SirTakobi commented on account_fiscal_year/models/account_fiscal_year.py
> +        that contains the two dates. (or False if no fiscal years)
This does not return `False` when no match is found, but an empty recordset of model `account.fiscal.year`.

2022-11-28 16:05 UTC, SirTakobi commented on account_fiscal_year/models/account_fiscal_year.py
> +        matches the selection"""
Maybe this line should be in the parenthesis? Or just removed?

2022-11-28 16:05 UTC, SirTakobi commented on account_fiscal_year/models/account_fiscal_year.py
> +    def _get_fiscal_year(self, company, date_from, date_to):
A method `account.fiscal.year._get_fiscal_year` looks like a bit vague in my opinion, maybe it can be moved in the company and called `_get_fiscal_year_by_date`?
Or it should have a name explaining what it does

2022-11-28 16:05 UTC, SirTakobi commented on account_fiscal_year/models/res_company.py
> +        AccountFiscalYear = self.env["account.fiscal.year"]
Variable names should use **snake_case**  both because it is the default for variables in Python (https://peps.python.org/pep-0008/#function-and-variable-names) and because the new code should fit in the style of its surroundings.

2022-11-28 16:05 UTC, SirTakobi commented on account_fiscal_year/i18n/account_fiscal_year.pot
> +#. module: account_fiscal_year
**po(t)** files should not be edited: they are managed by weblate. This is also stated in the guidelines:
> Pull requests should never directly modify .po files

(ref. https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#11translations)

2022-11-28 16:05 UTC, SirTakobi commented on account_fiscal_year/models/res_company.py
> +        today = fields.Date.today()
Can a test be added covering this new code?

2022-12-23 13:13 UTC, rafaelbn commented
Hello @legalsylvain , you have here pending answering the review 👍 🙏

2023-12-04 11:17 UTC, legalsylvain commented
> Hello @legalsylvain , you have here pending answering the review 👍 🙏

Hi @rafaelbn 
I totally missed this one. Thanks for the reminder ! 

I'll take a look.

2024-04-07 14:12 UTC, legalsylvain reviewed
Fixed. @rafaelbn is it now OK ?

2024-04-07 14:12 UTC, legalsylvain commented on account_fiscal_year/i18n/account_fiscal_year.pot
> +#. module: account_fiscal_year
Hi. I do not understand that rule.

How can I translate in my own instance, a new field created by an unmerged PR ? how do you do ?

2024-04-07 14:12 UTC, legalsylvain commented on account_fiscal_year/models/account_fiscal_year.py
> +    def _get_fiscal_year(self, company, date_from, date_to):
Fixed. Thanks.

2024-04-07 14:12 UTC, legalsylvain commented on account_fiscal_year/models/account_fiscal_year.py
> +        that contains the two dates. (or False if no fiscal years)
indeed. Fixed.

2024-04-07 18:38 UTC, rafaelbn commented
/ocabot rebase

2024-04-07 18:40 UTC, rafaelbn commented
@SirTakobi test pass could you please review the review? 😄 @legalsylvain attend comments!

2024-08-11 12:41 UTC, legalsylvain commented
@rafaelbn. Could we merge this one ? it is in production since 1 year without any problem.

2024-08-12 23:06 UTC, rafaelbn commented
Hello @SirTakobi ,

Could we please have your approval here?

Lot of work ❤️ 

Thank you! 😄

2024-08-14 20:03 UTC, rafaelbn commented
/ocabot merge minor

2024-08-14 20:04 UTC, rafaelbn commented
Done @legalsylvain !

2024-08-14 20:17 UTC, merged