16.0 mig account journal lock date
OCA/account-financial-tools pull request #1509
Opened 2022-11-28 09:07 UTC by RodrigoBM

#1472

2022-12-23 13:15 UTC, rafaelbn commented
/ocabot migration account_journal_lock_date

2023-01-09 12:01 UTC, alexis-via commented
I made a PR to improve this PR https://github.com/factorlibre/account-financial-tools/pull/7
It is a forward port of the fix that just landed in v14 : https://github.com/OCA/account-financial-tools/pull/1459

2023-01-09 12:08 UTC, alexis-via commented
When my PR will be merged, I'll approve this PR.

2023-01-09 15:41 UTC, RodrigoBM commented
@alexis-via PR merged. Thanks

2023-01-09 16:16 UTC, RodrigoBM commented
@alexis-via  the tests fail.
The odoo code only checks the lock date in the posted state.
If we want to keep the logic of the tests, I think it is necessary to check this in the creation.

```
    @api.model_create_multi
    def create(self, vals_list):
        res = super().create(vals_list)
        res._check_fiscalyear_lock_date()
        return res
```
what do you think?

2023-01-10 08:12 UTC, alexis-via approved these changes
code review

2023-01-13 10:41 UTC, RodrigoBM commented
@alexis-via  he borrado la comprobación de error en la creación  de account.move en los test, ya que los test estaban fallando.
En odoo la comprobacion de fecha bloqueo solo se realiza al pasar al estado posted, por lo cual ahora se permitira crear elementos en fecha de bloqueo.

2023-01-13 10:42 UTC, RodrigoBM commented
@alexis-via  I have deleted the error check on the creation of account.move in the tests, as the tests were failing.
In odoo the lock date check is only done when moving to the posted state, so now it will be allowed to create items on lock date.

2023-03-21 12:36 UTC, astirpe requested changes

2023-03-21 12:36 UTC, astirpe commented on account_journal_lock_date/tests/test_journal_lock_date.py
> +        with self.assertRaises(UserError):
@RodrigoBM do you mind to replace all the occurrences of `with self.assertRaises(UserError):` with:

```suggestion
        with self.assertRaisesRegex(UserError, ".*prior to and inclusive of the lock date.*"):
```

This way we ensure that the correct error is raised.

2023-03-21 22:22 UTC, RodrigoBM commented on account_journal_lock_date/tests/test_journal_lock_date.py
> +        with self.assertRaises(UserError):
done

2023-03-22 07:22 UTC, astirpe approved these changes

2023-03-29 08:03 UTC, RodrigoBM commented
@alexis-via can tou merge it? please

2023-05-05 11:27 UTC, RodrigoBM commented
@rafaelbn can tou merge it?

2023-06-06 13:31 UTC, alexis-via approved these changes

2023-06-06 13:32 UTC, alexis-via commented
/ocabot merge nobump

2023-06-06 13:39 UTC, merged