[16.0][FIX] account_move_name_sequence: computed fields raising warning
OCA/account-financial-tools pull request #1615
Opened 2023-03-15 10:47 UTC by remi-filament

Easy solution for #1614 by not computing related fields anymore thus warnings are not raised anymore for false gaps in sequence.

Still I guess we could find a way to preserve functionality to check if gap in sequence but cannot figure out how !

2023-03-15 18:16 UTC, moylop260 approved these changes
👍

2023-03-15 18:17 UTC, moylop260 commented
@luisg123v @hugho-ad @fernandahf

Please, review

2023-03-15 18:32 UTC, fernandahf approved these changes

2023-03-15 18:32 UTC, fernandahf commented
LGTM

2023-03-15 18:55 UTC, luisg123v requested changes

2023-03-15 18:55 UTC, luisg123v commented on account_move_name_sequence/models/account_move.py
> +    # highest_name, sequence_prefix, sequence_number are not needed any more
I think semantic was better before

2023-03-15 19:41 UTC, hugho-ad approved these changes

2023-03-15 20:08 UTC, alexis-via approved these changes

2023-03-15 20:29 UTC, RodrigoBM approved these changes

2023-03-16 03:17 UTC, moylop260 commented
/ocabot merge patch

2023-03-16 09:00 UTC, merged