[15.0][MIG] account_spread_cost_revenue
OCA/account-financial-tools pull request #1646
Opened 2023-05-29 03:39 UTC by Saran440

This module migration from standard and add PR enhance https://github.com/OCA/account-financial-tools/pull/1580

2023-07-07 08:30 UTC, astirpe commented on account_spread_cost_revenue/models/account_move_line.py
> +            "Move line: %(line_id)s (%(line_name)s), account code: %(account_code)s\n"
Why changing this line? This causes a failure when executing this line:  `msg += msg_line % (line.id, line.name, line.account_id.code)`

2023-08-02 06:14 UTC, BT-anieto requested changes
Thx for the PR! Try to reduce the changes at maximum when it is a migration. Moreover, format is not recommended for odoo translations. Could you chan ge it?

On the other hand, ensure that you squash the commits following https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

2023-08-02 06:14 UTC, BT-anieto commented on account_spread_cost_revenue/models/account_move_line.py
> +            "Move line: %(line_id)s (%(line_name)s), account code: %(account_code)s\n"
Agree with @astirpe. Could you check it please @Saran440 ?

2023-08-02 06:14 UTC, BT-anieto commented on account_spread_cost_revenue/models/account_move_line.py
> +                    ).format(len(template), line.display_name)
Do not change the translations. Format is not recommended.

2023-08-02 06:14 UTC, BT-anieto commented on account_spread_cost_revenue/models/account_spread.py
> +            msg_body = _("Unlinked invoice line '{}' (view {}).").format(
Do not change the translations. Format is not recommended

2023-08-02 06:14 UTC, BT-anieto commented on account_spread_cost_revenue/models/account_spread.py
> +            msg_body = _("Unlinked '{}' (invoice line {}).").format(
Do not change the translations. Format is not recommended

2023-08-02 06:14 UTC, BT-anieto commented on account_spread_cost_revenue/models/account_spread_template.py
> +                _("Followings are duplicated combinations,\n\n{}").format(
Do not change the translations. Format is not recommended

2023-09-13 09:44 UTC, Saran440 commented
@BT-anieto @astirpe Hi, Thank you for your review
I change it back to %(name)s because %s not support pre-commit it will error

```
account_spread_cost_revenue/models/account_move_line.py:100: [W8120(translation-positional-used), AccountMoveLine._check_spread_reconcile_validity] Translation method _('Move line: %s (%s), account code: %s\n') is using positional string printf formatting. Use named placeholder `_("%(placeholder)s")` instead.

account_spread_cost_revenue/models/account_move_line.py:148: [W8120(translation-positional-used), AccountMoveLine.create_auto_spread] Translation method _('Too many auto spread templates (%s) matched with the invoice line, %s') is using positional string printf formatting. Use named placeholder `_("%(placeholder)s")` instead.

account_spread_cost_revenue/models/account_spread.py:523: [W8120(translation-positional-used), AccountSpread._message_post_unlink_invoice_line] Translation method _("Unlinked invoice line '%s' (view %s).") is using positional string printf formatting. Use named placeholder `_("%(placeholder)s")` instead.

account_spread_cost_revenue/models/account_spread.py:532: [W8120(translation-positional-used), AccountSpread._message_post_unlink_invoice_line] Translation method _("Unlinked '%s' (invoice line %s).") is using positional string printf formatting. Use named placeholder `_("%(placeholder)s")` instead.

```

If you ok for this commit 33be08740bc71c36fdf420dc8ab312c2c749c788 i will merge this commit into 1 commit
What do you think?

2023-09-20 12:42 UTC, BT-anieto commented
Hi @Saran440 , you still need to follow https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests
You need to squash the commits and you can only push 2 commits: one of the refactor and another one with the code changes.

2023-10-18 03:52 UTC, Saran440 commented
I found a bug in module account_spread_cost_revenue.
Should we fixed it in this PR or next PR?

Step to error:
1. create spread templates
![Selection_001](https://github.com/OCA/account-financial-tools/assets/20896369/b0482823-5cc5-43d0-b1cf-aef0abbbf725)

2. create vendor bills and select the same account as the template > confirm
3. Go to 'Spread Costs/Revenues' > select spread cost that create from template > click 'create move' on line.
![Selection_002](https://github.com/OCA/account-financial-tools/assets/20896369/2d436eba-d7cb-401f-a333-23f4f872646a)
4. Error because It creates a new move and **a new template** (i test by comment error. it will create new template and move_type is entry)

2023-10-19 09:34 UTC, astirpe commented
@Saran440 I just ported your latest fix to V16 a6dae3b but with context passed in `def create_move()`. It's better to pass the context within `def create_move()` so that it also fixes the "Create All Moves" button (that calls the same method).

2023-10-24 04:02 UTC, Saran440 commented
@astirpe Fixed. I change it to pass context in function `def create_move()`. Thank you for reviewed.

2023-10-25 04:44 UTC, ps-tubtim approved these changes
Functional Test: Ok

2023-10-25 08:58 UTC, astirpe approved these changes

2023-11-29 12:12 UTC, kittiu commented
/ocabot merge nobump

2023-11-29 12:25 UTC, merged