[16.0][MIG] account_move_fiscal_month: Migration to 16.0
OCA/account-financial-tools pull request #1708
Opened 2023-08-04 06:16 UTC by BT-anieto

2023-08-04 08:53 UTC, BT-rmartin requested changes
Good job with the migration. Just some tiny improvements that you might consider

2023-08-04 08:53 UTC, BT-rmartin commented on account_fiscal_month/views/date_range_type.xml
> +    <record model="ir.ui.view" id="date_range_type_form_view">
Why not keeping same xml id as parent view_date_range_type_form_view and putting the id before the model?

2023-08-04 08:53 UTC, BT-rmartin commented on account_fiscal_month/views/date_range_type.xml
> +        <field name="name">date.range.type.tree (in account_fiscal_month)</field>
Same comment as above

2023-08-04 08:53 UTC, BT-rmartin commented on account_fiscal_month/__manifest__.py
> +    "data": ["data/date_range_type.xml", "views/date_range_type.xml"],
Better in several lines the depends and the data?

2023-08-04 08:53 UTC, BT-rmartin commented on account_fiscal_month/models/date_range_type.py
> +    fiscal_month = fields.Boolean(string="Is fiscal month?", readonly=True)
If it's readonly when is the the value assigned? Or the goal is just having the unique date.range.type created as business data as fiscal month?

2023-08-04 08:53 UTC, BT-rmartin commented on account_fiscal_month/models/date_range_type.py
> +            raise UserError(_("You can't delete date range type: " "Fiscal month"))
Couldn't you better delete the others and skip the deletion of this one?

2023-08-04 09:08 UTC, BT-anieto commented
@BT-rmartin As far as I know, all the changes you request should be addressed in another PR tagged with [IMP] after the migration. The migration should minimise the changes. The only 'big' change I've made is the setUp by setUpClass, since I have seen several times the change in other similar PRs.

If you are sure that your improvement can be addressed in this PR, I will do them because I agree with your suggestions

2023-08-04 09:28 UTC, BT-rmartin approved these changes
@BT-anieto You are right. Those changes should be done after merging probably. 
Regarding your change to setUpClass it's perfect, as now TransactionCase acts as the old SavepointCase and then as it's a common creation of data for all tests we will save some time in the execution

2023-08-17 10:31 UTC, BT-nfrancisco approved these changes

2023-08-29 08:40 UTC, BT-anieto commented
@OCA/accounting-maintainers Could it be merged?

2023-09-15 11:31 UTC, etobella commented
/ocabot migration account_fiscal_month

2023-09-15 11:33 UTC, etobella approved these changes
/ocabot merge nobump

2023-09-15 11:41 UTC, merged