[16.0][FIX] account_move_name_sequence. Inverse name.
OCA/account-financial-tools pull request #1742
Opened 2023-10-11 13:06 UTC by BT-anieto

The core compute function for the name is calling at the end the function self._inverse_name(), which updates the payment_reference when required. This code was currently missing, which causes the payment_reference not to be properly computed, for example, when using QR-Bills.

2023-10-11 14:06 UTC, BT-nfrancisco approved these changes

2023-10-11 19:56 UTC, moylop260 commented
You are right!

For record, the line referenced here is the following:
 - https://github.com/odoo/odoo/blob/4244331adb68a2eeec95d36c6e0c1a1cbb317ba4/addons/account/models/account_move.py#L701
 -

2023-10-11 19:57 UTC, moylop260 commented
/ocabot merge patch

2023-10-17 11:31 UTC, BT-anieto commented
Hello @moylop260 Why is it never merging it?

2023-10-17 15:49 UTC, luisg123v requested changes
Regarding commit message:
- Title shouldn't include version
- Title should follow the form `[TAG] module_name: short description`. But there's a dot after module name and short description only says "inverse name"
- Split lines to 72 characters

2023-10-18 05:53 UTC, BT-anieto commented
@luisg123v Is it proper now?

2023-10-18 15:43 UTC, moylop260 commented
/ocabot merge patch

2023-10-18 15:48 UTC, merged