[13.0] Replace 'Camptocamp SA' with 'Camptocamp'
OCA/account-financial-tools pull request #1901
Opened 2024-06-13 16:13 UTC by vvrossem

This pull request contains changes to replace 'Camptocamp SA' with 'Camptocamp' in __manifest__.py files for branch 13.0.

2024-06-13 16:45 UTC, etobella requested changes
Can you use a proper commit message please?

Something like `[FIX] account_fiscal_year: Change Camptocamp SA to Camptocamp`

2024-06-14 06:19 UTC, gurneyalex approved these changes

2024-06-14 06:21 UTC, gurneyalex commented on account_fiscal_year/__manifest__.py
>      "Odoo Community Association (OCA)",
```suggestion
    "author": "Agile Business Group, Camptocamp, Odoo Community Association (OCA)",
```

2024-06-14 06:34 UTC, gurneyalex commented
/ocabot merge patch

2024-06-14 06:37 UTC, etobella commented
@gurneyalex there are some comments to fix...

Please, do not merge until they are answered. Already, the 100 PR done by @vvrossem have the same issue. It is just a small typo change, but now it is easy to fix. otherwise, it will be kept like this for all history....

2024-06-14 06:41 UTC, pedrobaeza commented
And even more having 2 commits in this PR and the second one being a direct edition without even change the default commit message. If you are going to disturb the whole community with something that is not bringing value to it, at least do it correctly.

2025-05-25 12:33 UTC, closed without merging