[17.0][MIG] account_loan: Migration to 17.0
OCA/account-financial-tools pull request #1925
Opened 2024-08-15 20:46 UTC by JT-Odoo

2024-10-28 09:26 UTC, FernandoRomera commented
@JT-Odoo can you rebase for rebuild runbot?

2024-10-30 13:29 UTC, victoralmau requested changes
Please, cherry-pick https://github.com/OCA/account-financial-tools/pull/1952 to commit history and squash administrative commits.

2024-10-30 15:18 UTC, victoralmau requested changes

2024-10-30 15:18 UTC, victoralmau commented on account_loan/security/account_loan_security.xml
> +        </field>
```suggestion
        <field name="domain_force">[('company_id', 'in', company_ids + [False])]</field>
```

2024-10-30 15:18 UTC, victoralmau commented on account_loan/security/account_loan_security.xml
> +        </field>
```suggestion
        <field name="domain_force">[('company_id', 'in', company_ids + [False])]</field>
```

2024-10-30 15:18 UTC, victoralmau commented on account_loan/wizards/account_loan_generate_entries_view.xml
> +                    or
```suggestion
```

2024-10-30 15:18 UTC, victoralmau commented on account_loan/wizards/account_loan_increase_amount.xml
> +                    or
```suggestion
```

2024-10-30 15:18 UTC, victoralmau commented on account_loan/wizards/account_loan_pay_amount_view.xml
> +                    or
```suggestion
```

2024-10-30 15:18 UTC, victoralmau commented on account_loan/wizards/account_loan_post_view.xml
> +                    or
```suggestion
```

2024-11-04 07:11 UTC, victoralmau commented
Superseded by https://github.com/OCA/account-financial-tools/pull/1960

2024-11-04 07:12 UTC, closed without merging