[17.0][MIG] account_chart_update: Migration to 17.0
OCA/account-financial-tools pull request #1989
Opened 2024-12-13 08:37 UTC by victoralmau

Supersedes https://github.com/OCA/account-financial-tools/pull/1888

Migration to 17.0

Changes done:
- [x] Purge translations
- [x] Squash administrative commits
- [x] Change `name_get` to `_compute_display_name`
- [x] Change `attrs` to invisible/required
- [x] Adapt to the new `account.chart.template` system without records
- [ ] Test
- [ ] Improve similar methods to reduce code

@Tecnativa TT49275

2024-12-14 15:28 UTC, giarve approved these changes
![image](https://github.com/user-attachments/assets/46027cbe-56a7-4b44-9bd9-bff5f4ecacd9)

these 3 diffs always appear on runbot even after applying the wizard twice with the same chart. I do not know if you want to take a look. Everything else works good.

It is true though that not being able to edit the chart template from inside odoo is less convenient (to change the number of padding zeroes for example).

2024-12-14 15:28 UTC, giarve commented on account_chart_update/wizard/wizard_chart_update.py
> +                    # Extra domain to prevent encontrar el registro incorrecto
forgot to translate

2024-12-14 15:28 UTC, giarve commented on account_chart_update/wizard/wizard_chart_update.py
> +    xml_id = fields.Char()
only showing the xml id makes it harder to see new accounts and their name.
![image](https://github.com/user-attachments/assets/1d3eb544-a152-4e50-835a-fc5e9bcb32d3)

However, this is just an improvement so not requesting anything here. Also might be enough in 99% of the cases.

2024-12-17 12:17 UTC, victoralmau commented
> ![image](https://private-user-images.githubusercontent.com/45542433/395791476-46027cbe-56a7-4b44-9bd9-bff5f4ecacd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Mzc4NTcsIm5iZiI6MTczNDQzNzU1NywicGF0aCI6Ii80NTU0MjQzMy8zOTU3OTE0NzYtNDYwMjdjYmUtNTZhNy00YjQ0LTliZDktYmZmNWY0ZWNhY2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDEyMTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZTE5M2FmNzg5ZDgyZjIxNzdmNTAzZWFmZDMxNWUyMTczODA4OGM5Yzk0MjhiNjMwNzllYTliOWNiYzljOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y-HMyO6uHoYsLyBtQIIx-VT5n_HmP1p9LjpNjE_MEio)
> 
> these 3 diffs always appear on runbot even after applying the wizard twice with the same chart. I do not know if you want to take a look. Everything else works good.
> 
> It is true though that not being able to edit the chart template from inside odoo is less convenient (to change the number of padding zeroes for example).

Thanks, checked and fixed.

2024-12-17 17:08 UTC, giarve approved these changes

2024-12-19 10:47 UTC, DavidJForgeFlow approved these changes
Code LGTM! Seems to be working fine also :+1:

2024-12-23 11:34 UTC, LoisRForgeFlow approved these changes
Functional review :+1:

2024-12-24 12:44 UTC, pedrobaeza commented
/ocabot migration account_chart_update

2024-12-24 12:56 UTC, pedrobaeza requested changes
Several things:

- Is there any possibility to only load in the "Chart template" dropdown those that are already installed?
- When a tax group is not present (because for example is added in the last update), you get an error. You can force to happen trying to load Spanish taxes on generic CoA for example.

2025-01-07 12:15 UTC, victoralmau commented
> Several things:
> 
>     * Is there any possibility to only load in the "Chart template" dropdown those that are already installed?
> 
>     * When a tax group is not present (because for example is added in the last update), you get an error. You can force to happen trying to load Spanish taxes on generic CoA for example.

Changes done. The test error related to `_logger` I don't understand, any idea?

2025-01-08 08:25 UTC, victoralmau commented
The test error is finally fixed.

2025-01-10 08:03 UTC, syci commented
The wizard does not take into account the selected language.

https://github.com/Tecnativa/account-financial-tools/blob/b20ed9d7be75352d92041b2478c4af557fa769d4/account_chart_update/wizard/wizard_chart_update.py#L767

In a plan update the name of the taxes always appears in English.

![image](https://github.com/user-attachments/assets/cab21229-0283-468b-8b64-e9001b76d5ad)

With this change it works correctly.

```python
    def _load_data(self, model, data):
        """Process similar to the one in chart template."""
        template = self.env["account.chart.template"].with_context(
            default_company_id=self.company_id.id,
            allowed_company_ids=[self.company_id.id],
            tracking_disable=True,
            delay_account_group_sync=True,
            lang=self.lang,
        )
```

2025-01-10 09:51 UTC, victoralmau commented
> The wizard does not take into account the selected language.
> 
> https://github.com/Tecnativa/account-financial-tools/blob/b20ed9d7be75352d92041b2478c4af557fa769d4/account_chart_update/wizard/wizard_chart_update.py#L767
> 
> In a plan update the name of the taxes always appears in English.
> 
> ![image](https://private-user-images.githubusercontent.com/7081394/401879142-cab21229-0283-468b-8b64-e9001b76d5ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MDI2NzIsIm5iZiI6MTczNjUwMjM3MiwicGF0aCI6Ii83MDgxMzk0LzQwMTg3OTE0Mi1jYWIyMTIyOS0wMjgzLTQ2OGItOGI2NC1lOTAwMWI3NmQ1YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTBUMDk0NjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDAzN2U5Y2ZlMDAxNmE5M2M4MWM0YTVkODc4OWU1YTc4NDFiZTE4YWIzMGQ5MzE1ZWRhNTFjODJlYTVhNWE5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EUxl_LdXETQedMuuG5rud06Lh1scvRN4-0ZMeoNy6lA)
> 
> With this change it works correctly.
> 
> ```python
>     def _load_data(self, model, data):
>         """Process similar to the one in chart template."""
>         template = self.env["account.chart.template"].with_context(
>             default_company_id=self.company_id.id,
>             allowed_company_ids=[self.company_id.id],
>             tracking_disable=True,
>             delay_account_group_sync=True,
>             lang=self.lang,
>         )
> ```

Thanks for the comment, it has been solved so that the language is correctly taken into account (the suggestion you proposed was not enough).

2025-01-31 17:46 UTC, pedrobaeza commented
The language thing is still not working correctly. Do the following:

- On a fresh runboat (current one has been contaminated), load Spanish language, and switch to it.
- Run the chart update with Spanish selected.
- Result: The accounts in Spanish are update to the English names.

2025-02-04 13:33 UTC, victoralmau commented
> The language thing is still not working correctly. Do the following:
> 
>     * On a fresh runboat (current one has been contaminated), load Spanish language, and switch to it.
> 
>     * Run the chart update with Spanish selected.
> 
>     * Result: The accounts in Spanish are update to the English names.

Partially solved, this use case only happens when using `generic_coa` in a language other than English, because the data returned is not always translated, I have tried with for example l10n_es in Spanish and it works correctly (it does not detect any change).

2025-02-06 11:55 UTC, pedrobaeza commented
About the languages, I'm afraid is not working when you change to other language than the original one that was installed:

![Peek 06-02-2025 12-52](https://github.com/user-attachments/assets/8200f999-30a2-40b6-babc-cc191cadcaa5)

And another thing. As we have now a place where putting the button:

![imagen](https://github.com/user-attachments/assets/2f924c10-66c0-41f0-b90d-90e81c8c91fa)

don't create a separate section, but place it inside, and you can rename the existing one to "Reload for new elements", and the new one to "Update chart of accounts" (they can even be in the same row I think).

2025-02-06 16:39 UTC, victoralmau commented
> About the languages, I'm afraid is not working when you change to other language than the original one that was installed:
> 
Sorry, but I think there is an important confusion, when you select a language in the wizard (English) the data is checked in English (even if we are looking at things in Spanish). IMO this is coherent.
![ejemplo](https://github.com/user-attachments/assets/ae55f621-c7ad-4762-9a1d-f6d1986a6d7c)

2025-02-06 19:13 UTC, pedrobaeza commented
Oh, wait, I was starting from a bad assumption: that the account name is not translatable. But that's not the case anymore in this version. Thus, now I understand what you were saying. In this case, I think we should directly remove the language in the wizard, and check all the languages at the same time, and refresh it if any is changed.

2025-02-10 08:30 UTC, victoralmau commented
> don't create a separate section, but place it inside, and you can rename the existing one to "Reload for new elements", and the new one to "Update chart of accounts" (they can even be in the same row I think).

Changes done.

2025-02-10 08:31 UTC, victoralmau commented
> Oh, wait, I was starting from a bad assumption: that the account name is not translatable. But that's not the case anymore in this version. Thus, now I understand what you were saying. In this case, I think we should directly remove the language in the wizard, and check all the languages at the same time, and refresh it if any is changed.

Ok, changes done.

2025-02-10 19:48 UTC, syci commented
I have tried the update and the language now works well.

2025-02-11 07:37 UTC, pedrobaeza approved these changes
Thanks for all the changes and congratulations for the final result.

/ocabot merge nobump

2025-02-11 07:48 UTC, merged