[8.0] account_asset_management: fiscal years company specific
OCA/account-financial-tools pull request #331
Opened 2015-12-02 07:55 UTC by stijnh92

When no fiscal year is found for the start date on an asset, a query will be executed to search for the first available fiscal year in the system. But this query is not company specific. The company is found on the asset and this company id should be used in the query.

2015-12-02 08:46 UTC, luc-demeyer commented
:+1: 
Code review & testing ok.
Thanks for the contribution,

2017-05-29 10:30 UTC, adrienpeiffer commented
I don't really understand why travis failed. Perhaps we can try to rebuild this one.

2017-05-29 10:37 UTC, sbidoul requested changes

2017-05-29 10:37 UTC, sbidoul commented on account_asset_management/account_asset.py
> +            )
Can you please use `cr.execute("SELECT ...", (asset.company_id.id,))`

2017-06-05 20:29 UTC, luc-demeyer commented
I have a new version of the V8 account_asset_management module that is nearly ready for PR.
No more cr.executes, much faster and code refactored according to OCA guidelines (and aligned to upcoming V10 version of this module). 
I have planned a full day on friday for testing and expect to have the PR ready by friday evening.
Also most pending PR's are addressed in this one, hence we should be able to close them.

2022-01-30 12:20 UTC, closed without merging