[ADD] account_cost_center 8.0
OCA/account-financial-tools pull request #359
Opened 2016-02-23 15:52 UTC by astirpe

Adding module Cost Center.
This module allows the user to link every invoice line to a cost center providing an extra dimension for the analysis.

2017-01-03 09:52 UTC, nielsmiddeldorp approved these changes

2017-01-06 11:32 UTC, aschenkels-ictstudio commented
:+1:  Works for me

2017-01-09 10:43 UTC, hbrunn requested changes
some of the images violate [the branding rules](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#modules) of the OCA, in case you don't want to regenerate them, better remove them.

For all the `cost_center_id` fields in this module, I miss an index property. Is this a conscious choice?

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/__openerp__.py
> +    'summary': """Costcenter information for invoice lines""",
don't use multiline strings when not necessary

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/models/account_cost_center.py
> +    name = fields.Char(string='Title', required=True, size=64)
`size` is obsolete for char fields, better remove them

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/models/account_invoice.py
> +    def fields_view_get(self, cr, uid, view_id=None, view_type='form',
why no new api here?

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/models/account_invoice.py
> +                invoice_line = view_obj.xpath("//field[@name='invoice_line']")
you can replace this hack with https://github.com/OCA/server-tools/tree/8.0/base_view_inheritance_extension by now

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/models/account_invoice_line.py
> +            self._context.get('cost_center_id', None))
`None` already is the default for `dict.get`

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/security/ir.model.access.csv
> +access_account_cost_center_user,account.cost.center,model_account_cost_center,account.group_account_user,1,1,1,1
is it really a good idea to give the less privileged users full permissions on cost centers?

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/views/account_cost_center.xml
> +            <field name="name">account.cost.center.form</field>
let the orm generate a name if you don't pass anything informative

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/views/account_cost_center.xml
> +                                    <label for="name" string="Title"/>
it suffices to attach the class to the label

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/views/account_cost_center.xml
> +                        </notebook>
empty elements on reserve?

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/views/account_cost_center.xml
> +            <field name="name">account.cost.center.tree</field>
see above

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/views/account_cost_center.xml
> +                <form string="Cost Center" version="7.0">
the `string` and `version` attributes don't do anything here imho

2017-01-09 10:43 UTC, hbrunn commented on account_cost_center/views/account_cost_center.xml
> +            <field name="context">{'search_default_actual' : 1}</field>
what's this default good for?

2017-01-10 10:24 UTC, astirpe commented on account_cost_center/views/account_cost_center.xml
> +                        </notebook>
This was meant to be used by modules that extend this one.
I was creating some new modules that add pages on this form and I thought it was useful to have a notebook here.
Let say we remove this notebook, then if you have other two modules that add pages, you will need to couple those modules: one module adds the notebook, the other module extends from the first one adding pages.

I would prefer to keep this empty elements here in order to make inheritance easier.

2017-01-10 10:25 UTC, astirpe commented on account_cost_center/models/account_invoice.py
> +                invoice_line = view_obj.xpath("//field[@name='invoice_line']")
Let me try it ;)
I'll let you know!

2017-01-10 10:27 UTC, astirpe commented on account_cost_center/security/ir.model.access.csv
> +access_account_cost_center_user,account.cost.center,model_account_cost_center,account.group_account_user,1,1,1,1
I keep the full permissions for 'group_account_user'. Do you agree?

2017-01-10 10:28 UTC, astirpe commented on account_cost_center/views/account_cost_center.xml
> +                                    <label for="name" string="Title"/>
It seems this class doesn't have any effect here, I just removed the entire div.

2017-01-10 10:56 UTC, hbrunn commented on account_cost_center/views/account_cost_center.xml
> +                        </notebook>
for a module meant as base for a lot of others, that makes sense, yes

2017-01-10 10:59 UTC, hbrunn commented on account_cost_center/security/ir.model.access.csv
> +access_account_cost_center_user,account.cost.center,model_account_cost_center,account.group_account_user,1,1,1,1
that's in line with having analytic accounts being fully accessible to account_user, so yes, makes sense

2017-01-11 08:42 UTC, hbrunn commented on account_cost_center/models/account_move_line.py
> +        select=True,
it's called `index` by now: https://github.com/OCA/OCB/blob/8.0/openerp/fields.py#L139

2017-01-11 08:43 UTC, hbrunn commented on account_cost_center/models/account_invoice_line.py
> +        select=True,
here too

2017-01-11 08:44 UTC, hbrunn commented
nice! As soon as the indexes are fixed, we can merge in my opinion

2017-01-11 12:28 UTC, hbrunn approved these changes

2017-01-11 12:28 UTC, hbrunn commented
nice! Any plans for further work or should I merge?

2017-01-11 13:59 UTC, astirpe commented
For me this module is complete. Thanks!

2017-01-11 14:04 UTC, merged

2017-01-12 15:24 UTC, astirpe commented
Thanks to you all for the reviews!
If you are interested, you can review the PR #442 containing the porting of account_cost_center to V9