[10.0] Port account_partner_required
OCA/account-financial-tools pull request #426
Opened 2016-12-07 14:33 UTC by alexis-via

This PR also adds a technical module account_type_menu that adds a menu entry for account types. We had this pb when porting the module account_analytic_required and a menu entry for account types was added inside the module account_analytic_required... which is not a good solution because other module can't benefit from it. Once this PR will be merged, I'll do another PR to remove the menu entry from account_analytic_required and make it depend on the module "account_type_menu".

2016-12-07 15:30 UTC, sbidoul commented on account_partner_required/models/account.py
> +                ('never', _('Never'))]
This method is not necessary with the new api since there is selection_add, but it may be good to keep it for backward compatibility. As you wish.

2016-12-07 15:33 UTC, sbidoul approved these changes
(code review)

Thanks Alexis!

2016-12-07 16:19 UTC, alexis-via commented
I fully agree with your remark @sbidoul, I removed that method.

2016-12-07 16:53 UTC, pedrobaeza commented
Shouldn't this be called `account_account_partner_required`?

2016-12-07 17:16 UTC, alexis-via commented
@pedrobaeza I know you like changing module name, but on this one, you don't convince me at all !

2016-12-07 17:26 UTC, pedrobaeza commented
Well, the logic is there: area (`account`) + object (`account`) + function (`partner_required`). This is why we have for example the module `sale_order_type` and not `sale_type`. This is the scheme I always try to apply to all my developments.

2016-12-07 17:46 UTC, sbidoul commented
I'm fine with `account_partner_required`. The double `account` name does not add any benefit. 
There must be something in https://www.python.org/dev/peps/pep-0020/ for these kind of situations.

2016-12-07 17:50 UTC, pedrobaeza commented
OK, no special problem in leaving as is.

2016-12-07 17:52 UTC, pedrobaeza commented on account_type_menu/README.rst
> +This module adds a menu entry *Account Type* under *Accounting > Configuration > Accounting*, because this menu entry doesn't exists in the official *account* module of Odoo 10.
It should `Account Types` in plural, following all menus convention.

2016-12-07 18:21 UTC, adrienpeiffer approved these changes
:+1: (Code review and functional test)

2017-01-10 15:16 UTC, yvaucher requested changes
Just a little error with strings otherwise LGTM

2017-01-10 15:16 UTC, yvaucher commented on account_partner_required/models/account.py
> +                          line.name))
Warning you included the variable part in the translatable string

_("..." % (...) ) -> _("...")  % (...)

2017-01-10 15:16 UTC, yvaucher commented on account_partner_required/models/account.py
> +                          line.partner_id.name))
Same thing here

2017-01-10 15:36 UTC, alexis-via commented on account_partner_required/models/account.py
> +                          line.name))
nice catch ! Fixed.

2017-01-10 15:47 UTC, yvaucher approved these changes

2017-01-10 15:50 UTC, merged