[9.0] [MIG] account_balance_line module
OCA/account-financial-tools pull request #428
Opened 2016-12-16 09:48 UTC by cubells

- Updated README
- Updated views
- Updated file structure

cc @Tecnativa

2016-12-17 09:35 UTC, pedrobaeza requested changes
I have tried on runbot and I'm afraid is not working.

2016-12-17 09:35 UTC, pedrobaeza commented on account_balance_line/README.rst
> +For further information, please visit:
This is not needed

2016-12-17 09:35 UTC, pedrobaeza commented on account_balance_line/__openerp__.py
> +    'version': '9.0.0.1.0',
9.0.1.0.0

2016-12-17 09:35 UTC, pedrobaeza commented on account_balance_line/i18n/es.po
>  #: field:account.move.line,line_balance:0
This translation is not valid for version 9. Please export from v9 and translate again.

2016-12-17 09:35 UTC, pedrobaeza commented on account_balance_line/README.rst
> +Usage
Add some usage instructions saying something like 
```
#. If you're an accounting adviser, enable developer mode and go to Accounting > Adviser > Journal items.
#. Or open an account or a partner, and click on Action > Journal items.
#. Filter or group by account.
#. You will see a column named "Balance" with the balance of the line.
```

2016-12-17 09:35 UTC, pedrobaeza commented on account_balance_line/README.rst
> +Add a balance total for grouped lines in move line view.
s/Add/This module adds

2016-12-17 19:12 UTC, pedrobaeza commented on account_balance_line/README.rst
> +If you're an accounting adviser, enable developer mode and go to
Put the markers I have told you in the comment: `#.`. They serve for making an unordered bullet list in RST (like `<ul>` in HTML)

2016-12-17 19:14 UTC, pedrobaeza commented
I'm doing the last comment by myself for not disturbing you more.

2016-12-17 19:15 UTC, pedrobaeza commented
Curious that the module doesn't get installed on runbot. I have to install it manually by myself. @moylop260, do you have any idea why this happens?

2016-12-17 19:17 UTC, pedrobaeza approved these changes

2016-12-17 20:39 UTC, moylop260 commented
> Curious that the module doesn't get installed on runbot. I have to install it manually by myself. @moylop260, do you have any idea why this happens?

I saw that this project has enabled [UNIT_TEST="1"](https://github.com/oca/account-financial-tools/blob/9.0/.travis.yml#L20)
This feature test all modules but delete the previous database, then we will have the database with the latest module tested.

2016-12-18 00:40 UTC, pedrobaeza commented
Rebased for applying runbot patch in this PR

2016-12-18 07:06 UTC, cubells commented
@pedrobaeza Thanks Pedro.

2016-12-28 17:18 UTC, jjscarafia commented
Hi @cubells Why to create a new field and not use current v9 balance field? (I think it was not present on v8 or at least it was not stored).
Check [field definition on v9](https://github.com/odoo/odoo/blob/9.0/addons/account/models/account_move.py#L368) and [computed method](https://github.com/odoo/odoo/blob/9.0/addons/account/models/account_move.py#L309) They are the same as "line_balance" defined in this module as far as I can see.

Perhups only add "balance" in views would be enough.

2016-12-28 17:46 UTC, pedrobaeza commented
Indeed the compute method is the same. That's inherited from v8, where this computed field doesn't exist. Then the best is to just to show the field.

2016-12-28 19:02 UTC, moylop260 commented on account_balance_line/views/account_move_line_view.xml
> +                <attribute name="context">{'group_by': 'account_id', 'invisible_balance': False}</attribute>
Use `translation="off"` more info https://github.com/odoo/odoo/issues/14497

2016-12-28 19:02 UTC, moylop260 commented on account_balance_line/views/account_move_line_view.xml
> +                <attribute name="context">{'invisible_balance': False}</attribute>
Use `translation="off"` more info https://github.com/odoo/odoo/issues/14497

2016-12-28 19:03 UTC, moylop260 commented on account_balance_line/i18n/pt_PT.po
> +msgid "{'group_by': 'account_id', 'invisible_balance': False}"
Remove this translation after: `translation="off"`

2016-12-28 19:04 UTC, moylop260 approved these changes
Small translation comment
After that LGTM

2016-12-28 19:04 UTC, moylop260 commented on account_balance_line/i18n/pt_PT.po
> +msgid "{'invisible_balance': False}"
same case

2017-01-03 10:18 UTC, cubells commented
Done @moylop260

2017-01-04 17:42 UTC, damendieta approved these changes

2017-01-07 16:34 UTC, merged