[MIG] Migration of the module account_invoice_required (use the PR#404)
OCA/account-financial-tools pull request #467
Opened 2017-03-23 13:05 UTC by sylvainvh

2017-03-23 16:27 UTC, pedrobaeza commented
Have you seen my comments for v9? Do they apply here?

2017-03-28 09:00 UTC, sylvainvh commented
@pedrobaeza nope but I'll see that now !

2017-03-28 09:22 UTC, sylvainvh commented
@pedrobaeza I seen all your comments and I think that everything was fixed by @angelmoya . Is it true ?

2017-03-28 10:48 UTC, angelmoya commented on account_invoice_tax_required/models/account_invoice.py
> +                _('No Taxes Defined!\n %s') % (errors_full_string)
@sylvainvh I update this yesterday to prevent translation broken, and join errors with '\n'

2017-03-28 11:31 UTC, sylvainvh commented
@angelmoya I just cherry-picked your last commit. It should be fine now :)

2017-04-01 15:36 UTC, pedrobaeza requested changes
Last commit doesn't correspond to this PR, and you should check latest changes from 9.0. Anyway, it still breaks the build and I'm just checking how to make it compatible with demo data.

2017-06-07 12:44 UTC, sylvainvh commented
This module has been migrate by Kitti U. (from ecosoft).
We can close this PR

2017-06-07 12:44 UTC, closed without merging