10.0 mig account balance line
OCA/account-financial-tools pull request #468
Opened 2017-03-24 11:43 UTC by mourad-ehm

wip. The context is not propagated correctly from search view to tree view. thus the fields balance is never displayed. The 10 version change some thing about the use of context propagation ?

2017-08-30 08:03 UTC, sergio-teruel approved these changes

2017-08-30 09:30 UTC, sergio-teruel commented
@mourad-ehm Hi, yes you are rigth about the context propagation, at this time i don't know about context propagation in v10, but, Can we add commits to this PR? We can show the balance field always.. 
what do you think?

2017-08-30 09:32 UTC, sergio-teruel requested changes
Context propagation fault

2017-09-08 07:26 UTC, pedrobaeza approved these changes

2017-09-08 07:26 UTC, merged