[8.0] constraints opening balance
OCA/account-financial-tools pull request #502
Opened 2017-06-15 09:17 UTC by NL66278

Forward ported from PR for 7.0: https://github.com/OCA/account-financial-tools/pull/494

2017-06-17 00:33 UTC, elicoidal requested changes
needs rework to fit OCA standards

2017-06-17 00:33 UTC, elicoidal commented on account_constraints/__init__.py
>  ##############################################################################
remove header or use short ones

2017-06-17 00:33 UTC, elicoidal commented on account_constraints/__init__.py
>  ##############################################################################
add README

2017-06-17 00:33 UTC, elicoidal commented on account_constraints/wizards/__init__.py
> +# © 2017 Therp BV <http://therp.nl>
Please recheck date and copyright

2017-06-17 07:46 UTC, sbidoul approved these changes

2017-06-17 20:02 UTC, NL66278 commented on account_constraints/wizards/__init__.py
> +# © 2017 Therp BV <http://therp.nl>
Wizard written by me in this PR. So copyright and date are correct.

2017-06-17 20:06 UTC, NL66278 commented on account_constraints/__init__.py
>  ##############################################################################
This is just a small bugfix PR, so I would think this might not be the place to make unchanged parts of the code standards compliant.

2017-06-17 20:07 UTC, NL66278 commented on account_constraints/__init__.py
>  ##############################################################################
But I did change the header, as that was in a file changed anyway.

2017-06-18 23:43 UTC, elicoidal approved these changes

2017-08-21 14:31 UTC, MiquelRForgeFlow approved these changes

2022-06-19 12:26 UTC, closed without merging