[MIG] base_vat_optional_vies: Migration to 10.0
OCA/account-financial-tools pull request #507
Opened 2017-06-23 17:56 UTC by chienandalu

Optional validation of VAT via VIES
===================================

This module extends base_vat module features allowing to know if VIES
validation was passed or not.

cc @Tecnativa

Migrated from: https://github.com/OCA/account-financial-tools/pull/427

2017-06-30 18:01 UTC, pedrobaeza requested changes

2017-06-30 18:01 UTC, pedrobaeza commented on base_vat_optional_vies/models/res_partner.py
> +    def __init__(self, pool, cr):
Don't do this hack

2017-06-30 18:01 UTC, pedrobaeza commented on base_vat_optional_vies/models/res_partner.py
> +            if (not self.env.context.get('avoid_check_vat') and
Call super always. In this case, you can call it when VIES bypass is not activated. Put also a mechanism for avoiding this special check when on test mode and not testing specifically this module. Use a similar technique than https://github.com/OCA/bank-payment/blob/c5b093fb5ef1df31a699e49c90db646db115b44a/account_payment_transfer_reconcile_batch/models/payment_order.py#L28

2017-06-30 18:01 UTC, pedrobaeza commented on base_vat_optional_vies/models/res_partner.py
> +    @api.multi
This hack shouldn't be needed

2017-06-30 18:01 UTC, pedrobaeza commented on base_vat_optional_vies/tests/test_res_partner.py
> +    # AEA: Can't use this test in Travis, VIES checking returns always False
Remove this if not used, but try again to see. Maybe you can mock the call to VIES checking

2017-06-30 19:07 UTC, pedrobaeza commented on base_vat_optional_vies/models/res_partner.py
> +            if not self.env.context.get('test_vies'):
You are ignoring config['test_enable'] as specified and still not calling super...

2017-07-03 08:44 UTC, chienandalu commented
@pedrobaeza Yes, calling the super there required to make use of the base check methods. Wich is better and more simple anyway. Take a look now.

2017-07-03 10:33 UTC, pedrobaeza commented on base_vat_optional_vies/models/res_partner.py
> +                super(ResPartner, partner).check_vat()
I don't get why do you need to still overwrite this if you have already touched the other methods.

2017-07-03 11:23 UTC, chienandalu commented
@pedrobaeza It avoids checking again vat here: https://github.com/Tecnativa/account-financial-tools/blob/180d9c01a3e0c57dd8b1495c4af5e20d4bb08940/base_vat_optional_vies/models/res_partner.py#L83
It also avoids check on child contacts (wich I'm not sure if it's necessary/correct)

2017-07-03 15:19 UTC, pedrobaeza approved these changes

2017-08-07 18:05 UTC, luismontalba approved these changes
Tested on runbot

2017-08-08 13:52 UTC, merged