WIP: Currency rate inverted
OCA/account-financial-tools pull request #508
Opened 2017-06-24 05:16 UTC by jcdrubay

2017-09-01 07:41 UTC, congdpt requested changes

2017-09-01 07:41 UTC, congdpt commented on currency_rate_inverted/models/res_currency.py
> +from openerp import api, fields, models
Could you change `openerp` to `odoo`? Because we use this module for version 10

2018-06-22 03:09 UTC, jcdrubay commented
This has been implemented in a better way in v11: https://github.com/OCA/currency/tree/11.0/currency_rate_inverted

Should we close this PR? I don't think I will work on it anymore.

2018-06-22 03:11 UTC, pedrobaeza commented
Then closing this. Thanks any way for your work and a backport can be possible in any moment.

2018-06-22 03:11 UTC, closed without merging