[11.0][MIG] account reversal: Migration to 11.0
OCA/account-financial-tools pull request #557
Opened 2017-10-14 18:13 UTC by pedrobaeza

Migration commit is d67419f 

@Tecnativa

2017-10-14 18:22 UTC, pedrobaeza commented
@luismontalba @cubells please review

2017-10-16 14:15 UTC, cubells requested changes

2017-10-16 14:15 UTC, cubells commented on account_reversal/README.rst
> +As in Odoo v11c, if you select an entry from Accounting > Adviser > Journal Entries,
The exact menu is `Accounting > Adviser > Accounting entries > Journal Entries`

2017-10-16 14:15 UTC, cubells commented on account_reversal/__manifest__.py
> +        "account",
To be able to do tests, I had to install account_invoicing.

2017-10-16 14:15 UTC, cubells commented on account_reversal/i18n/account_reversal.pot
> +# Translation of OpenERP Server.
Don't you have to remove this file?

2017-10-17 07:26 UTC, pedrobaeza commented
@cubells thanks for the review. Changes done

2017-10-17 08:37 UTC, cubells approved these changes
:+1: 

LGTM

code review and test.

2017-10-17 08:38 UTC, pedrobaeza commented
@luismontalba please review

2017-10-17 18:38 UTC, luismontalba commented
Can't access runbot, neither admin/admin nor demo/demo

2017-10-17 19:40 UTC, pedrobaeza commented
Runbot seems to be having issues. Please try tomorrow afternoon rebuilding.

2017-10-18 17:38 UTC, luismontalba commented
Some issue than yesterday ...

2017-11-21 16:38 UTC, luismontalba approved these changes
Tested on runbot

2017-11-21 16:43 UTC, pedrobaeza commented
Closing as a later PR has been merged.

2017-11-21 16:43 UTC, closed without merging