11.0 mig account invoice constraint chronology
OCA/account-financial-tools pull request #590
Opened 2017-12-19 16:31 UTC by OpenCode

Migrate account_invoice_constraint_chronology to Odoo 11.0

2017-12-22 10:14 UTC, etobella approved these changes
LGTM :+1: 
just two comments

2017-12-22 10:14 UTC, etobella commented on account_invoice_constraint_chronology/tests/test_account_constraint_chronology.py
> +# -*- coding: utf-8 -*-
No longer necessary on py files

2017-12-22 10:14 UTC, etobella commented on account_invoice_constraint_chronology/tests/test_account_constraint_chronology.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
https

2017-12-22 11:43 UTC, OpenCode commented
@etobella Done! Thank you for your review :)

2018-01-09 11:40 UTC, JordiBForgeFlow requested changes

2018-01-09 11:40 UTC, jbeficent commented on account_invoice_constraint_chronology/README.rst
> +* there are draft invoices with an anterior date
replace 'anterior' with 'prior'

2018-01-09 11:40 UTC, jbeficent commented on account_invoice_constraint_chronology/README.rst
> +* there are validated invoices with a posterior date
replace 'posterior' with 'later'

2018-01-10 09:02 UTC, rgarnau requested changes

2018-01-10 09:02 UTC, rgarnau commented on account_invoice_constraint_chronology/model/account_invoice.py
> +                                          "with a date posterior to %s.") %
as @jbeficent mentions before, change 'posterior'.

2018-01-10 09:02 UTC, rgarnau commented on account_invoice_constraint_chronology/README.rst
> +   :target: http://www.gnu.org/licenses/agpl-3.0-standalone.html
https

2018-01-10 09:02 UTC, rgarnau commented on account_invoice_constraint_chronology/README.rst
> +To configure this module, go to the menu *Accounting > Configuration > Journals > Journals* and activate the option *Check Chronology* on the relevant journals. After the installation of the module,
Replace *Accounting > Configuration > Journals > Journals*
for *Accounting/Invoicing > Configuration > Accounting > Journals*

2018-01-11 16:51 UTC, jbeficent commented
@OpenCode Do you prefer us to send a PR with these minor fixes suggested?

2018-01-12 09:51 UTC, jbeficent commented
As @OpenCode is not actively managing the PR we have built on top of his branch to correct the minor fixed and proposed the PR https://github.com/OCA/account-financial-tools/pull/600, so closing this one.

2018-01-12 09:51 UTC, closed without merging

2018-01-12 17:00 UTC, OpenCode commented
@jbeficent I was working on requestes. I saw @rgarnau solved it with another PR. Ok.