[IMP] account_chart_update: update taxes when children are differents
OCA/account-financial-tools pull request #593
Opened 2017-12-26 16:39 UTC by cubells

With these changes, account_chart_update will update taxes if their children are not the same than template ones.

updated spanish translation

cc @Tecnativa

2017-12-27 08:33 UTC, pedrobaeza requested changes
Apart from the rest of the comments, change module version and include tests.

2017-12-27 08:33 UTC, pedrobaeza commented on account_chart_update/i18n/es.po
> +msgstr "los impuestos hijos no son los mismos."
Upper

2017-12-27 08:33 UTC, pedrobaeza commented on account_chart_update/i18n/es.po
> +"Determina si el impuesto es seleccionable. Note: 'Ninguno' significa que un "
s/Note/Nota

2017-12-27 08:33 UTC, pedrobaeza commented on account_chart_update/i18n/es.po
> +msgstr "Las cuentas exitentes están actualizadas. Las cuentas se han buscado por código."
s/exitentes/existentes

2017-12-27 08:33 UTC, pedrobaeza commented on account_chart_update/i18n/es.po
> +"Si está marcado, el asistente continuará al siguiente paso incluos si hay "
s/incluos/incluso

2017-12-27 08:33 UTC, pedrobaeza commented on account_chart_update/i18n/es.po
> +"Si deja estas opciones marcadas, el asistente no solamente crearé los nuevos "
s/crearé/creará

2017-12-27 08:33 UTC, pedrobaeza commented on account_chart_update/i18n/es.po
> +"acuerdo a la plan de cuentas seleccionado."
s/a la/al

2017-12-27 08:33 UTC, pedrobaeza commented on account_chart_update/i18n/es.po
> +msgstr "Actualitzar posiciones fiscales"
s/Actualitzar/Actualizar

2017-12-27 08:33 UTC, pedrobaeza commented on account_chart_update/i18n/es.po
> +msgstr "Actualizar registros?"
Opening question symbol

2017-12-27 08:33 UTC, pedrobaeza commented on account_chart_update/wizard/wizard_chart_update.py
> +            if real.children_tax_ids.ids != template.children_tax_ids.ids:
These IDs of course are not going to be the same, as one are taxes and the other are taxes templates. You have to use the same comparison as for parent taxes.

2018-02-26 13:33 UTC, pedrobaeza commented
@cubells please rebase, resolve conflicts and attend commits.

2018-07-11 21:06 UTC, sbidoul commented
At line 375, account_chart_update ignore child taxes. Do you know why it is so? @pedrobaeza

2018-07-12 06:29 UTC, pedrobaeza commented
I think it's because each tax is evaluated independently, counting also their parent field, so children tax will be compared and if different parent, then present it to update. No need to check reverse one2many field.

2018-09-21 00:50 UTC, pedrobaeza commented
Superseeded by #693

2018-09-21 00:50 UTC, closed without merging