[IMP] Add sum of total amount due
OCA/account-financial-tools pull request #598
Opened 2018-01-10 10:22 UTC by cubells

It does make sense to remove the sum of residual in multiple currencies, but it is necessary to add the sum of residual amount. It's important information for user.

cc @Tecnativa

2018-01-10 11:20 UTC, pedrobaeza requested changes

2018-01-10 11:20 UTC, pedrobaeza commented on account_invoice_currency/views/account_invoice.xml
> +            <field name="residual_company_signed" string="Amount Due" sum="Amount Due"/>
Don't put `string` and let the field label.

2018-01-10 11:20 UTC, pedrobaeza commented on account_invoice_currency/views/account_invoice.xml
> +            <field name="residual_company_signed" string="Amount Due" sum="Amount Due"/>
Don't put `string` and let the field label.

2018-01-10 11:21 UTC, pedrobaeza commented on account_invoice_currency/views/account_invoice.xml
> +            <attribute name="invisible">True</attribute>
I'm thinking that we should keep both fields, because both information is interesting.

2018-01-10 14:39 UTC, pedrobaeza requested changes

2018-01-10 14:39 UTC, pedrobaeza commented on account_invoice_currency/__manifest__.py
>                "Serv. Tecnol. Avanzados - Pedro M. Baeza, "
Remove this one

2018-01-10 14:39 UTC, pedrobaeza commented on account_invoice_currency/__manifest__.py
> +    'version': "10.0.1.0.1",
It should be 10.0.1.10, as it requires update

2018-01-10 14:48 UTC, cubells commented
I've squashed all commits.

2018-02-12 17:15 UTC, luismontalba approved these changes
Tested on runbot

2018-02-12 22:12 UTC, pedrobaeza approved these changes

2018-02-12 22:13 UTC, merged