[11.0][MIG] account credit control dunning fees
OCA/account-financial-tools pull request #607
Opened 2018-02-02 12:13 UTC by grindtildeath

2018-02-19 11:24 UTC, simahawk requested changes
LGTM, small things

2018-02-19 11:24 UTC, simahawk commented on account_credit_control_dunning_fees/README.rst
> +.. figure:: path/to/local/image.png
drop if not needed

2018-02-19 11:24 UTC, simahawk commented on account_credit_control_dunning_fees/view/policy_view.xml
> +          <group>
Do you need both groups? If yes, name at least the outer one.

2018-02-19 11:25 UTC, simahawk commented
tests are failing because of missing dep from the other PR: add separated commit to drop later before merge w/ oca_depencies.txt pointing to that PR's branch.

2018-02-26 14:37 UTC, simahawk approved these changes

2018-03-01 14:19 UTC, ghost approved these changes

2018-03-01 14:19 UTC, arkostyuk commented on account_credit_control_dunning_fees/README.rst
> +Just install it.
drop this section?

2018-03-05 09:39 UTC, guewen approved these changes

2018-03-05 09:51 UTC, fclementic2c commented
Please add by default to this screen all accounts with the type 'receivables'.
Of course, user must be able to remove any accounts and this change must be persistent.

![image](https://user-images.githubusercontent.com/5735158/36968501-feb7e36c-2062-11e8-9245-78908615c8b7.png)

2018-04-24 06:16 UTC, simahawk commented
@grindtildeath @yvaucher #603  merged, can we close this too?

2018-04-24 07:33 UTC, grindtildeath commented
@simahawk For me, migration is done, and this PR can be merged.

2018-05-17 11:19 UTC, merged