[11.0][mig] account_tax_analysis
OCA/account-financial-tools pull request #660
Opened 2018-07-02 08:48 UTC by sbidoul

Look at the last two commits.

Migration plus a small improvement (which I will backport to 10 when this is merged).

2018-07-02 10:16 UTC, rousseldenis commented on account_tax_analysis/models/account_move_line.py
> +        related='account_id.user_type_id', store=True)
@sbidoul Is this shouldn't be readonly?

2018-07-03 06:33 UTC, sbidoul commented on account_tax_analysis/models/account_move_line.py
> +        related='account_id.user_type_id', store=True)
@rousseldenis done

2018-07-03 07:31 UTC, rousseldenis approved these changes
Code review

2019-04-21 22:43 UTC, tbaden requested changes
thanks for the work 👍 
i did a code review. just a small change and some optional, nice to have, changes

2019-04-21 22:43 UTC, tbaden commented on account_tax_analysis/__manifest__.py
> +    "website": "http://www.camptocamp.com",
please change website to: https://github.com/OCA/account-financial-tools

2019-04-21 22:43 UTC, tbaden commented on account_tax_analysis/wizard/account_tax_analysis_view.xml
> +        id="menu_action_account_vat_declaration_analysis"/>
id pattern (optional)
> Use the following patterns, where <model_name> is the name of the model that the menu, view, etc. belongs to (e.g. for a res.users form view, the name would be res_users_view_form):
> 
> For a menu: <model_name>_menu

2019-04-21 22:43 UTC, tbaden commented on account_tax_analysis/wizard/account_tax_analysis_view.xml
> +        id="menu_account_vat_declaration_analysis"/>
id pattern (optional)
> Use the following patterns, where <model_name> is the name of the model that the menu, view, etc. belongs to (e.g. for a res.users form view, the name would be res_users_view_form):
> 
> For a menu: <model_name>_menu

2019-04-21 22:43 UTC, tbaden commented on account_tax_analysis/wizard/account_tax_analysis_view.xml
> +    <record id="action_account_vat_declaration_analysis" model="ir.actions.act_window">
id pattern (optional)
> Use the following patterns, where <model_name> is the name of the model that the menu, view, etc. belongs to (e.g. for a res.users form view, the name would be res_users_view_form):
> 
> For an action: the main action respects <model_name>_action. Others are suffixed with _<detail>, where detail is  
> an underscore lowercase string explaining the action (should not be long). This is used only if multiple actions are declared for the model.

2019-04-21 22:43 UTC, tbaden commented on account_tax_analysis/wizard/account_tax_analysis_view.xml
> +    <record id="view_account_vat_declaration_analysis" model="ir.ui.view">
id pattern (optional)

> Use the following patterns, where <model_name> is the name of the model that the menu, view, etc. belongs to (e.g. for a res.users form view, the name would be res_users_view_form):
> 
> For a view: <model_name>_view_<view_type>, where view_type is kanban, form, tree, search, ...

2019-04-21 22:43 UTC, tbaden commented on account_tax_analysis/views/account_move_line.xml
> +    <record id="action_view_tax_analysis" model="ir.actions.act_window">
id pattern (optional)

> Use the following patterns, where <model_name> is the name of the model that the menu, view, etc. belongs to (e.g. for a res.users form view, the name would be res_users_view_form):
> 
> For an action: the main action respects <model_name>_action. Others are suffixed with _, where detail is
> an underscore lowercase string explaining the action (should not be long). This is used only if multiple actions are declared for the model.

2019-04-21 22:43 UTC, tbaden commented on account_tax_analysis/views/account_move_line.xml
> +    <record id="view_move_line_tree_tax_analysis" model="ir.ui.view">
id pattern (optional)

> Use the following patterns, where <model_name> is the name of the model that the menu, view, etc. belongs to (e.g. for a res.users form view, the name would be res_users_view_form):
> 
> For a view: <model_name>view<view_type>, where view_type is kanban, form, tree, search, ...

2019-04-21 22:43 UTC, tbaden commented on account_tax_analysis/views/account_move_line.xml
> +    <record id="view_account_move_line_filter_vat_analysis" model="ir.ui.view">
id pattern (optional)

> Use the following patterns, where <model_name> is the name of the model that the menu, view, etc. belongs to (e.g. for a res.users form view, the name would be res_users_view_form):
> 
> For a view: <model_name>view<view_type>, where view_type is kanban, form, tree, search, ...

2022-10-02 12:34 UTC, closed without merging