[11.0][MIG] account_asset_management_method_number_end : Migration to v11
OCA/account-financial-tools pull request #704
Opened 2018-10-02 11:30 UTC by grindtildeath

Requires :
 - [ ] #698

2018-10-05 13:47 UTC, simahawk requested changes

2018-10-05 13:47 UTC, simahawk commented on account_asset_management_method_number_end/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/92/10.0
same: please use new readme structure

2018-10-05 13:47 UTC, simahawk commented on account_asset_management_method_number_end/__manifest__.py
> +    'website': 'http://www.noviat.com',
https://github.com/OCA/account-financial-tools

2018-10-05 13:47 UTC, simahawk commented on account_asset_management_method_number_end/models/account_asset.py
> +    method_number = fields.Integer(
what about a mixin to avoid copy/paste? :)

2018-10-05 13:47 UTC, simahawk commented on account_asset_management_method_number_end/tests/test_account_asset_management.py
> +    def setUp(self):
do you really need to load this for every test? Otherwise pls use SavepointCase + setUpClass

2018-10-11 16:40 UTC, pedrobaeza commented
Why isn't this integrated on main module?

2018-10-12 10:14 UTC, grindtildeath commented
@pedrobaeza I suppose the reason is an historic one.
@luc-demeyer Should we merge these functions into the base module or is there a good reason to keep it separated ?

2018-10-13 17:51 UTC, luc-demeyer commented
There is good reason to keep this separate.
The two methods added by this module are NOT supposed to be used for Financial Asset Management purposes. 
In case your customer wants to generate accounting entries for Cost or Revenue spreading than it becomes usefull.

An example:
As a company you may receive insure bills for car insurance on twice a year.
If you have many company cars you may prefer to split the cost of such a bill over the insurance cost duration (6 month) -> use a 'cost spreading' top level view account for reporting purposes and an asset profile with time method number', number = 6, period = month and the appropriate general accounts will do the job.

2018-10-13 18:00 UTC, pedrobaeza commented
Well, the "number of depreciations" methods is a general one that can be used as well for financial assets, and as I saw you on the code sprint, my customers are using it as well as the percentage method. I can agree about the "date end", but at the end, the purpose for what it's used is not the main question, as this adds little overcharge being added to the main module (an if on the appropriated methods), but being more complicated using a modular approach (manifest, new module, new PR...).

2018-10-14 13:50 UTC, luc-demeyer commented
If there is a legal requirement in Spain to support the 'number' method for managing financial assets (hence NOT cost/revenue spreading) than we should add it to the main module. As far as I know financial assets always need to be depreciated based upon fiscal years (full years or pro-rata temporis). The number method allows to depreciate over e.g. 6 months, or 13 months, ... which I think is not allowed (also in Spain) unless those 6 months are accidently the end of the fiscal year.
I don't think we should promote a method that allows customers to make mistakes if the current base module methods are aligned with legal requirements.

The official addons account_asset module has a (rather large) number of flaws, hence you need to use the number method on the official module in some cases to circumvent the fact that their calculations are not fiscal year based.

2018-10-22 10:33 UTC, astirpe commented
For the spreading of costs and revenues I'm proposing a dedicated module. See PR https://github.com/OCA/account-financial-tools/pull/704

2018-10-23 10:32 UTC, yung-wang commented
@luc-demeyer @pedrobaeza In the Netherlands it is also allowed to used 'number' or date based (fiscal years), so i would propose to pushed this to the main. Let the end-user decided how they want to manage their financial assets. I worked with a lot of accountants and they prefer to calculate the depreciation of the assets based on numbers (like 5 years x12 = 60 periods). You just fill in the start date of the depreciation and based on the numbers of periods, the system will automatically calculate the depreciation per period.
If the purpose of this is only for cost spreading invoices, then why put this module in the Assets category? This shouldn't belong here then.

There is already a cost spreading / accrual like functionality. See about PR #715 and [account-closing](https://github.com/OCA/account-closing)

2019-08-16 11:29 UTC, grindtildeath commented
@luc-demeyer Just fixed the travis issue and rebased, so this should be good.

2021-05-18 10:30 UTC, MiquelRForgeFlow commented
@grindtildeath hello everybody, will this PR proceed forward to has green CI?

2022-11-06 12:29 UTC, closed without merging