[10.0][FIX] account_asset_management: domain in multicompany
OCA/account-financial-tools pull request #714
Opened 2018-10-18 09:55 UTC by astirpe

In a multicompany environment, an user who has access to multiple companies is able to select accounts and journals of multiple companies in the assets profile form. This can easily lead to mistakes in the definition of an asset profile.

With this PR the user can only read/select accounts and journals belonging to the company already set in the asset profile.

This PR is similar to the one I opened for the standard _account_asset_ module: see https://github.com/odoo/odoo/pull/26578.

2018-10-23 11:30 UTC, grindtildeath reviewed
@astirpe Is this really needed ? 
Shouldn't we be able to select a record from a children company as the record rules allow ? 
cc @luc-demeyer

2018-10-23 12:25 UTC, astirpe commented
@grindtildeath to me it looks like it's really needed. Try to have a look in the code of the standard Odoo: you will notice that for accounts and journals they only filter by one company and not by company children.

2018-10-23 21:21 UTC, luc-demeyer commented
👎 
Whenever you are in a multi-company environments it's recommended to NOT use the admin (uid=1) user for accounting config. If you use another user the standard Odoo record rules do the job.
Hence this PR is imho not needed. I also think that we'll have a lot of work if we need to secure all accounting config settings in all Odoo and OCA modules so that the uid=1 can be used safely for accounting config purposes.
Another remark: by adding the domains on the view level, the domain filters in the underlying account_asset_profile.py module get broken, hence in it's current form this PR cannot be merged.

2018-10-23 23:13 UTC, pedrobaeza commented
@luc-demeyer you can access several companies without being admin if you have a company hierarchy and you are on the parent company. This can be useful if put at field level instead. Any way, it's not very advisable to use Odoo using parent company (unless only viewing data) until multi-company support improves, changing its approach to be totally driven by company per document.

2018-10-24 07:04 UTC, astirpe commented
We faced the issue in a multicompany environment, where an account manager user does the accounting for all the companies of an holding company and its child companies.

2018-10-24 07:05 UTC, astirpe commented
@luc-demeyer I updated the domain definitions in the view, would you give it a try?

2018-10-24 07:25 UTC, astirpe commented
Travis failure not related with this PR. Also other 2 PRs on branch 10.0 are failing for the same reason.
cc @OCA/accounting-maintainers

2018-10-24 07:46 UTC, luc-demeyer commented
Looking to the updated diff: I think we should put the domain definition on one place (hence only on view or only on ORM field level).
Imho this PR is not necessary since there are so many places where accounting settings can be misconfigured when working with parent/child hierarchy on companies. But on the other hand, adding this extra security on the domain doesn't hurt.

2018-10-25 15:49 UTC, grindtildeath commented
@astirpe The goal seems legit, but IMO would be better to keep the domain at field level only. 
However I'm not sure it makes much change to define the company_id domain at field level, so I don't really know... :man_shrugging:

2018-10-30 09:25 UTC, luc-demeyer commented
:+1:

2020-06-25 08:03 UTC, enricostano commented
@astirpe @luc-demeyer what's the status on this? We're facing the same problem in v12 with multi-company and almost open a new [PR](https://github.com/OCA/account-financial-tools/compare/12.0...coopdevs:fix/asset_profile_company?expand=1).

Is there anything we can do to move this forward?

2020-07-11 13:36 UTC, luc-demeyer approved these changes

2020-07-12 11:27 UTC, pedrobaeza requested changes
And squash all the commits together

2020-07-12 11:27 UTC, pedrobaeza commented on account_asset_management/models/account_asset_profile.py
> -        domain=[('deprecated', '=', False)],
Put the domain here, but with quotes:

`domain="[('company_id', '=', company_id), ('type', '=', 'general')]"`

2020-07-13 10:11 UTC, pedrobaeza commented
Flake8 error due to line length.

2020-08-03 13:43 UTC, astirpe commented
Travis failure fixed by https://github.com/OCA/account-financial-tools/pull/1001

2022-11-13 12:30 UTC, closed without merging