[FIX] ValueError: min() arg is an empty sequence
OCA/account-financial-tools pull request #749
Opened 2019-01-08 14:45 UTC by bodedra

Issue Reference: https://github.com/OCA/account-financial-tools/issues/748

2019-01-08 20:22 UTC, pedrobaeza requested changes

2019-01-08 20:22 UTC, pedrobaeza commented on account_loan/model/account_loan.py
> +        if lines:
for reducing the diff, do:
```suggestion
        if not lines:
            return
```

2019-01-09 17:49 UTC, bodedra commented
@pedrobaeza Comment attended!

2019-01-09 18:01 UTC, pedrobaeza approved these changes

2019-01-14 09:08 UTC, acsonefho approved these changes
LGTM (code only)

2019-01-18 09:01 UTC, merged