[11.0][ADD]
OCA/account-financial-tools pull request #750
Opened 2019-01-09 16:48 UTC by RodrigoBM

2019-01-09 17:44 UTC, pedrobaeza commented
Please preserve commit history adapting technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0 (as this comes from other branch different than 10.0).

2019-01-10 11:23 UTC, RodrigoBM commented
Hi @pedrobaeza,
I have already made the changes you mentioned.
Thank

2019-01-10 12:05 UTC, pedrobaeza commented
OK, you can squash Transbot commit together using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

Now reviewers should review the PR.

2019-01-16 22:24 UTC, rafaelbn requested changes

2019-01-16 22:24 UTC, rafaelbn commented on base_vat_optional_vies/__manifest__.py
> +              'FactorLibre',
Migrating a module don't means being author. Only in some cases when a refactoring o something significant. In any case if a Technical review say you have done a significant work then the author should be under Tecnativa and above OCA.

2019-01-16 22:24 UTC, rafaelbn commented on base_vat_optional_vies/__manifest__.py
> +    'website': 'https://www.tecnativa.com',
Change website to https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L11

2019-01-21 14:32 UTC, RodrigoBM commented on base_vat_optional_vies/__manifest__.py
> +              'FactorLibre',
okay, I change it

2019-01-21 14:32 UTC, RodrigoBM commented on base_vat_optional_vies/__manifest__.py
> +    'website': 'https://www.tecnativa.com',
okay, I change it

2019-03-18 10:39 UTC, RodrigoBM commented
@rafaelbn  Could you please check? Please

2019-06-04 12:01 UTC, Tardo requested changes
Thanks for the work, it would be nice if you used the new README structure.

2019-06-04 12:01 UTC, Tardo commented on base_vat_optional_vies/views/res_partner_view.xml
> +</odoo>
Add empty line

2020-02-03 11:10 UTC, RodrigoBM commented on base_vat_optional_vies/views/res_partner_view.xml
> +</odoo>
Hi Tardo, I have already added empty line and updated README, i hope the README is fine.

2022-11-16 00:18 UTC, rafaelbn commented
Sorry 😢

2022-11-16 00:19 UTC, rafaelbn commented
/ocabot rebase

2022-11-16 00:20 UTC, rafaelbn commented
Sorry @RodrigoBM I miss this one. If you want to rebase I can test it with pleasure

2022-11-16 00:22 UTC, rafaelbn approved these changes
Thanks for the changes

2022-11-18 20:02 UTC, rafaelbn commented
Check travis @RodrigoBM 
```

$ export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}

4.08s$ travis_install_nightly

DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.

DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.

ERROR: Could not find a version that satisfies the requirement pylint-plugin-utils==0.7 (from -r /home/travis/maintainer-quality-tools/travis/pylint_odoo_requirements.txt (line 1)) (from versions: 0.1, 0.1.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.6, 0.3, 0.4, 0.5, 0.6)

ERROR: No matching distribution found for pylint-plugin-utils==0.7 (from -r /home/travis/maintainer-quality-tools/travis/pylint_odoo_requirements.txt (line 1))

The command "travis_install_nightly" failed and exited with 1 during .

Your build has been stopped.
```

2022-11-22 13:07 UTC, RodrigoBM commented
The error comes from Travis. This error is also in other repisitories like https://app.travis-ci.com/github/OCA/account-financial-reporting/jobs/522506817 and I don't know how to solve it.

2022-11-23 21:12 UTC, rafaelbn commented
@RodrigoBM I understand but if nobody fix it bot don't allow to merge it 😢

2022-11-29 07:42 UTC, RodrigoBM commented
Hi @rafaelbn, I have tried to remove travis and switch to github actions [here](https://github.com/OCA/account-financial-tools/pull/1511). But I have a problem with the account_spread_contract module, it doesn't pass the test.

2023-05-07 12:21 UTC, closed without merging