[12.0][account_asset_management] add hook method _get_amount_linear
OCA/account-financial-tools pull request #903
Opened 2019-10-17 14:48 UTC by jbeficent

Used in https://github.com/OCA/l10n-spain/pull/1206

2019-10-17 15:18 UTC, pedrobaeza approved these changes

2019-10-17 15:19 UTC, bodedra approved these changes

2019-10-20 10:22 UTC, luc-demeyer requested changes
This logic doesn't take into account leap years.
The hook should not change the current behavious of the module where e.g. 2000 EUR depreciated over 2 years gives 1000 EUR per year. If one of years is a leap year you now return 2000/(365+366)*365 = 998,63.
Hence we should change the hook to return an amount / nbr years or otherwise make the logic more complex (with extra leap year param as proposed in PR 902).

2019-10-20 10:38 UTC, jbeficent commented
Before we merge this PR I think it's better that we agree on https://github.com/OCA/account-financial-tools/pull/902

2019-10-25 13:09 UTC, jbeficent commented
Closing in favor of https://github.com/OCA/account-financial-tools/pull/852

2019-10-25 13:09 UTC, closed without merging