[13.0][MIG] account_fiscal_position_vat_check
OCA/account-financial-tools pull request #997
Opened 2020-05-19 11:07 UTC by Garcicasti

2020-05-21 07:03 UTC, juliap98 approved these changes
Funcional review ok

2020-05-21 07:30 UTC, ValentinVinagre requested changes
Please review the changes into versions.

2020-05-21 07:30 UTC, ValentinVinagre commented on account_fiscal_position_vat_check/models/account_invoice.py
> +    _inherit = "account.invoice"
This model doesn't exist in v.13 now is "account.move"

2020-05-21 07:30 UTC, ValentinVinagre commented on account_fiscal_position_vat_check/models/account_invoice.py
> +    def action_move_create(self):
This function doesn't exist in v.13

2020-05-21 07:30 UTC, ValentinVinagre commented on account_fiscal_position_vat_check/models/account_move.py
> +    def action_move_create(self):
the same, doesn't exist in v.13

2020-07-22 06:23 UTC, misern2 commented
@Garcicasti please could you attend the comments.

Thanks!

2023-06-18 12:22 UTC, closed without merging